#redsi配置信息-单节点
spring:
  redis:
    database: 0
    cluster:
      #redis客户端名称,jedis、redisson有该属性，lettuce没有
      clientName: 'redis-client-name'
      #Redis服务器访问密码
      password: 123456
      #集群模式下，逗号分隔的键值对（主机：端口）形式的服务器列表
      nodes: 127.0.0.1:6379
      #连接超时，指的是连接一个url的连接等待时间
      connectionTimeout: 1000
      #读取数据超时，指的是连接上一个url，获取response的返回等待时间
      soTimeOut: 1000
      #连接失败重试次数
      maxAttempts: 2
      #集群模式下，集群最大转发的数量
      max-redirects: 3
      #是否启用SSL连接，AWS ElastiCache服务要开启SSL才可以正常访问
      ssl: false
      #是否开启集群模式，按环境加载对应的客户端模式
      clusterEnable: false
    pool:
      max-active: 50  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10  # 连接池中的最大空闲连接
      min-idle: 5 # 连接池中的最小空闲连接

#redsi配置信息-集群
#spring:
#  redis:
#    database: 0
#    cluster:
#      #redis客户端名称,jedis、redisson有该属性，lettuce没有
#      clientName: 'redis-client-name'
#      #Redis服务器访问密码
#      password: 123456
#      #集群模式下，逗号分隔的键值对（主机：端口）形式的服务器列表
#      nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
#      #连接超时，指的是连接一个url的连接等待时间
#      connectionTimeout: 1000
#      #读取数据超时，指的是连接上一个url，获取response的返回等待时间
#      soTimeOut: 1000
#      #连接失败重试次数
#      maxAttempts: 2
#      #集群模式下，集群最大转发的数量
#      max-redirects: 3
#      #是否启用SSL连接，AWS ElastiCache服务要开启SSL才可以正常访问
#      ssl: true
#      #是否开启集群模式，按环境加载对应的客户端模式
#      clusterEnable: true
#    pool:
#      max-active: 50  # 连接池最大连接数（使用负值表示没有限制）
#      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 10  # 连接池中的最大空闲连接
#      min-idle: 5 # 连接池中的最小空闲连接